# Generated by Django 6.0.6 on 2026-07-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_name', models.CharField(max_length=100)),
                ('stock_quantity', models.PositiveIntegerField()),
                ('minimum_stock', models.PositiveIntegerField()),
            ],
        ),
    ]
